# =============================================================================
# TTE package: hands-on tutorial
#
# 1. Target trial emulation for SGLT2 inhibitors versus DPP-4 inhibitors
#    Outcome: all-cause death
# =============================================================================
#
# Motivating study:
# Noma H, Goto A, Sugimoto T, Sunada H, Oda F, Maeda M, Fukuda H.
# Real-world effectiveness of SGLT2 inhibitors in adults aged 75 years or
# older: a target trial emulation. Age and Ageing. 2026; in press.
#
# Design represented by the synthetic example:
# - active-comparator new-user design
# - adults aged 75 years or older with type 2 diabetes
# - initiation of an SGLT2 inhibitor versus initiation of a DPP-4 inhibitor
# - primary outcome: all-cause death
# - one-month induction period
# - intention-to-treat (ITT) and per-protocol (PP) estimands
#
# The package contains a small synthetic dataset generated by computer
# simulation:
#   DPP-4i: 497 individuals
#   SGLT2i: 203 individuals
#   Total: 700 individuals
#
# IMPORTANT:
# - These data are entirely synthetic and contain no actual patient records.
# - Numerical results from this tutorial are not estimates from the motivating
#   clinical study and must not be interpreted as real drug-effect estimates.
#
# This tutorial estimates all analysis weights from the observed synthetic
# data. The reference weights bundled in the dataset are used only in the
# optional comparison at the end.
#
# TTE version 1.1.1 or later is assumed.
# =============================================================================


# Install once after the package becomes available on CRAN:
# install.packages("TTE")

library(TTE)

options(width = 110)

packageVersion("TTE")


# -----------------------------------------------------------------------------
# 1-1. Load and inspect the data
# -----------------------------------------------------------------------------
#
# `SGLT2_baseline` contains one row per treatment initiator and is used for
# the baseline treatment model and covariate-balance assessment.
# `SGLT2` is a person-month dataset used for censoring models, pooled
# discrete-time outcome models, and weighted survival curves.
# The code also verifies that all variables required by the tutorial are present,
# creates working copies, fixes the displayed treatment order, and checks the
# person-period structure before any weights are estimated.

data(SGLT2_baseline)
data(SGLT2)

dim(SGLT2_baseline)
head(SGLT2_baseline, 20)

dim(SGLT2)
head(SGLT2, 6)


table(SGLT2_baseline$treatment)

with(SGLT2, tapply(Y_death, treatment, sum))

required_baseline <- c(
  "id", "trial", "A", "treatment", "age", "female", "bmi", "hba1c",
  "egfr", "proteinuria", "prior_heart_failure", "prior_stroke",
  "recent_hospitalization", "trial_period"
)

required_long <- c(
  "id", "trial", "time", "A", "treatment", "Y_death",
  "stay_ltfu", "stay_adherent", "pp_at_risk",
  "age", "female", "bmi", "hba1c", "egfr", "proteinuria",
  "prior_heart_failure", "prior_stroke", "recent_hospitalization",
  "trial_period"
)

setdiff(required_baseline, names(SGLT2_baseline))
setdiff(required_long, names(SGLT2))

stopifnot(all(required_baseline %in% names(SGLT2_baseline)))
stopifnot(all(required_long %in% names(SGLT2)))

sglt2_baseline <- SGLT2_baseline
sglt2_long <- SGLT2

sglt2_baseline$treatment <- factor(
  sglt2_baseline$A,
  levels = c(0, 1),
  labels = c("DPP-4i", "SGLT2i")
)

sglt2_long$treatment <- factor(
  sglt2_long$A,
  levels = c(0, 1),
  labels = c("DPP-4i", "SGLT2i")
)

check_sglt2 <- check_tte(
  sglt2_long,
  id = id,
  trial = trial,
  time = time,
  event = Y_death,
  treatment = A
)

print(check_sglt2)


# -----------------------------------------------------------------------------
# 1-2. Estimate the baseline treatment weight
# -----------------------------------------------------------------------------
#
# `est_wt()` estimates stabilized weights by default.
# For each individual, the numerator is the marginal probability of the observed
# treatment and the denominator is the conditional probability given measured
# baseline covariates.
# Weight components are left untruncated here; truncation is applied only after
# the treatment and censoring components have been multiplied.

wt_treatment_sglt2 <- est_wt(
  A ~
    age + I(age^2) +
    female +
    bmi +
    hba1c + I(hba1c^2) +
    egfr +
    proteinuria +
    prior_heart_failure +
    prior_stroke +
    recent_hospitalization +
    trial_period,

  data = sglt2_baseline,
  type = "treatment",
  stabilize = TRUE,
  truncate = c(0, 1)
)

summary(wt_treatment_sglt2)
plot(wt_treatment_sglt2)


# -----------------------------------------------------------------------------
# 1-3. Assess baseline covariate balance
# -----------------------------------------------------------------------------
#
# `balance_wt()` compares standardized mean differences before and after
# baseline treatment weighting. An absolute SMD of 0.10 is often used as a
# diagnostic threshold, but achieving that threshold does not rule out
# unmeasured confounding.

balance_sglt2 <- balance_wt(
  A ~
    age +
    female +
    bmi +
    hba1c +
    egfr +
    proteinuria +
    prior_heart_failure +
    prior_stroke +
    recent_hospitalization +
    trial_period,

  data = sglt2_baseline,
  weights = wt_treatment_sglt2
)

print(balance_sglt2)
summary(balance_sglt2, threshold = 0.10)
plot(balance_sglt2, threshold = 0.10)


# -----------------------------------------------------------------------------
# 1-4. Map the baseline weight to person-month records
# -----------------------------------------------------------------------------
#
# The baseline dataset has one row per individual, whereas the long dataset
# has multiple rows per individual. The code matches on the `id`-`trial` pair
# and copies each untruncated baseline treatment weight to every corresponding
# person-month.

key_baseline <- paste(
  sglt2_baseline$id,
  sglt2_baseline$trial,
  sep = ":"
)

key_long <- paste(
  sglt2_long$id,
  sglt2_long$trial,
  sep = ":"
)

baseline_index <- match(key_long, key_baseline)

stopifnot(!anyNA(baseline_index))

sglt2_long$w_treatment_est <- weights(
  wt_treatment_sglt2,
  which = "untruncated"
)[baseline_index]

summary(sglt2_long$w_treatment_est)


# -----------------------------------------------------------------------------
# 1-5. Estimate the loss-to-follow-up weight for the ITT analysis
# -----------------------------------------------------------------------------
#
# `stay_ltfu = 1` means that the individual remains observed through the
# next interval. Interval-specific stabilized censoring factors are accumulated
# within each `id`-`trial` trajectory.
# With `lag = 1`, the outcome contribution in interval t receives the weight
# accumulated through the start of that interval.
# In an applied study, time-varying predictors must be measured before the
# censoring decision they are intended to predict.

wt_ltfu_itt_sglt2 <- est_wt(
  stay_ltfu ~
    A +
    splines::ns(time, df = 3) +
    age +
    female +
    bmi +
    hba1c +
    egfr +
    proteinuria +
    prior_heart_failure +
    prior_stroke +
    recent_hospitalization +
    trial_period,

  numerator =
    stay_ltfu ~
    A +
    splines::ns(time, df = 3) +
    trial_period,

  data = sglt2_long,
  type = "censoring",
  id = id,
  trial = trial,
  time = time,
  cumulative = TRUE,
  lag = 1,
  stabilize = TRUE,
  truncate = c(0, 1)
)

summary(wt_ltfu_itt_sglt2)

head(as.data.frame(wt_ltfu_itt_sglt2), 10)


# -----------------------------------------------------------------------------
# 1-6. Construct and diagnose the final ITT weight
# -----------------------------------------------------------------------------
#
# The final ITT weight is the product of the baseline treatment weight and
# the cumulative loss-to-follow-up weight. The combined weight is truncated at
# the 1st and 99th percentiles.
# `diagnose_wt()` summarizes the distribution, effective sample size, treatment-
# specific behavior, and the weighted risk set over follow-up.

wt_itt_sglt2 <- combine_wt(
  sglt2_long$w_treatment_est,
  wt_ltfu_itt_sglt2,
  truncate = c(0.01, 0.99),
  normalize = "none"
)

sglt2_long$w_itt_est <- weights(wt_itt_sglt2)

summary(sglt2_long$w_itt_est)

diag_itt_sglt2 <- diagnose_wt(
  w_itt_est,
  data = sglt2_long,
  treatment = treatment,
  time = time,
  id = id,
  trial = trial
)

print(diag_itt_sglt2)

old_par <- par(no.readonly = TRUE)
par(mfrow = c(1, 2))
plot(diag_itt_sglt2, type = "weights")
plot(diag_itt_sglt2, type = "risk_set")
par(old_par)


# -----------------------------------------------------------------------------
# 1-7. Fit the weighted pooled discrete-time model for the ITT effect
# -----------------------------------------------------------------------------
#
# The outcome model uses a complementary log-log link and a flexible
# natural-spline function of follow-up time. The exponentiated coefficient for
# `A` is interpreted as a discrete-time hazard ratio.
# Inference is clustered by the original individual because each person
# contributes multiple person-month records.

fit_death <- discsurvreg(
  Y_death ~
    A +
    splines::ns(time, df = 3) +
    trial_period,

  data = sglt2_long,
  id = id,
  weights = w_itt_est,
  family = quasibinomial(link = "cloglog"),
  var_method = "standard"
)

print(fit_death)
summary(fit_death)

confint(fit_death, parm = "A", eform = TRUE)


# -----------------------------------------------------------------------------
# 1-8. Standardize the ITT model to absolute risks
# -----------------------------------------------------------------------------
#
# `std_tte()` creates counterfactual copies of the baseline population in
# which everyone initiates DPP-4i and everyone initiates SGLT2i. Predicted
# interval-specific event probabilities are accumulated and averaged over the
# target population.
# The output includes treatment-specific survival and cumulative risk, the risk
# difference, risk ratio, and a time-specific NNT or NNH.

std_death <- std_tte(
  fit_death,

  data = sglt2_baseline,

  treatment = A,
  time = time,

  times = 0:59,

  values = c(0, 1),
  labels = c("DPP-4i", "SGLT2i")
)

summary(std_death, horizon = 36)

summary(std_death, horizon = 60)

plot(std_death, measure = "risk")


# -----------------------------------------------------------------------------
# 1-9. Estimate an IPW-weighted Kaplan-Meier curve for the ITT effect
# -----------------------------------------------------------------------------
#
# The standardized curve is model based. The weighted Kaplan-Meier curve is
# estimated directly from weighted risk sets and event counts in the IPW
# pseudo-population.
# The two estimators need not be identical. Large discrepancies can signal
# outcome-model misspecification, extreme weights, limited positivity, or a very
# small weighted risk set late in follow-up.

km_death <- curve_tte(
  sglt2_long,
  time = time,
  event = Y_death,
  treatment = treatment,
  weights = w_itt_est,
  type = "km",
  id = id,
  trial = trial
)

summary(km_death, time = 36)
summary(km_death, time = 60)

plot(km_death, measure = "risk")


# -----------------------------------------------------------------------------
# 1-10. Create the per-protocol risk set
# -----------------------------------------------------------------------------
#
# For the PP estimand, follow-up is artificially censored when an individual
# deviates from the assigned treatment strategy.
# Only intervals with `pp_at_risk == 1` are retained. `stay_pp` indicates that
# the individual remains observed and adherent through the next interval.

sglt2_pp <- subset(
  sglt2_long,
  pp_at_risk == 1
)

sglt2_pp$stay_pp <- as.integer(
  sglt2_pp$stay_ltfu == 1 &
  sglt2_pp$stay_adherent == 1
)

table(sglt2_pp$stay_pp)


# -----------------------------------------------------------------------------
# 1-11. Estimate the joint censoring weight for the PP analysis
# -----------------------------------------------------------------------------
#
# Loss to follow-up and protocol deviation are modeled jointly.
# The denominator should contain predictors of treatment continuation,
# discontinuation, switching, and the outcome. This teaching dataset has limited
# time-varying clinical information, so the model is intentionally simplified.
# A substantive analysis should use appropriately lagged time-varying values
# such as updated HbA1c, kidney function, hospitalizations, concomitant drugs,
# and frailty measures when available.

wt_censor_pp_sglt2 <- est_wt(
  stay_pp ~
    A +
    splines::ns(time, df = 3) +
    age +
    female +
    bmi +
    hba1c +
    egfr +
    proteinuria +
    prior_heart_failure +
    prior_stroke +
    recent_hospitalization +
    trial_period,

  numerator =
    stay_pp ~
    A +
    splines::ns(time, df = 3) +
    trial_period,

  data = sglt2_pp,
  type = "censoring",
  id = id,
  trial = trial,
  time = time,
  cumulative = TRUE,
  lag = 1,
  stabilize = TRUE,
  truncate = c(0, 1)
)

summary(wt_censor_pp_sglt2)


# -----------------------------------------------------------------------------
# 1-12. Construct and diagnose the final PP weight
# -----------------------------------------------------------------------------
#
# The final PP weight multiplies the baseline treatment weight by the
# cumulative joint censoring weight and truncates the result at the 1st and 99th
# percentiles.

wt_pp_sglt2 <- combine_wt(
  sglt2_pp$w_treatment_est,
  wt_censor_pp_sglt2,
  truncate = c(0.01, 0.99),
  normalize = "none"
)

sglt2_pp$w_pp_est <- weights(wt_pp_sglt2)

summary(sglt2_pp$w_pp_est)

diag_pp_sglt2 <- diagnose_wt(
  w_pp_est,
  data = sglt2_pp,
  treatment = treatment,
  time = time,
  id = id,
  trial = trial
)

print(diag_pp_sglt2)

old_par <- par(no.readonly = TRUE)
par(mfrow = c(1, 2))
plot(diag_pp_sglt2, type = "weights")
plot(diag_pp_sglt2, type = "risk_set")
par(old_par)


# -----------------------------------------------------------------------------
# 1-13. Fit the weighted pooled discrete-time model for the PP effect
# -----------------------------------------------------------------------------
#
# The PP outcome model is fitted in the PP risk set using the estimated
# `w_pp_est`. Its treatment coefficient estimates the hazard ratio under
# continued adherence, subject to the measured-confounding and positivity
# assumptions required for the artificial-censoring analysis.

fit_death_pp <- discsurvreg(
  Y_death ~
    A +
    splines::ns(time, df = 3) +
    trial_period,

  data = sglt2_pp,
  id = id,
  weights = w_pp_est,
  family = quasibinomial(link = "cloglog"),
  var_method = "standard"
)

print(fit_death_pp)
summary(fit_death_pp)

confint(fit_death_pp, parm = "A", eform = TRUE)


# -----------------------------------------------------------------------------
# 1-14. Standardize the PP model to absolute risks
# -----------------------------------------------------------------------------
#
# The fitted PP outcome model is standardized over the original baseline
# population to estimate the cumulative risk under sustained DPP-4i and sustained
# SGLT2i strategies.

std_death_pp <- std_tte(
  fit_death_pp,
  data = sglt2_baseline,
  treatment = A,
  time = time,
  times = 0:59,
  values = c(0, 1),
  labels = c("DPP-4i", "SGLT2i")
)

summary(std_death_pp, horizon = 36)
summary(std_death_pp, horizon = 60)

plot(std_death_pp, measure = "risk")


# -----------------------------------------------------------------------------
# 1-15. Estimate a weighted Kaplan-Meier curve for the PP effect
# -----------------------------------------------------------------------------
#
# This curve is calculated directly from the PP risk set using the estimated
# PP weights. It provides a less outcome-model-dependent comparison with the
# standardized PP risk curve.

km_death_pp <- curve_tte(
  sglt2_pp,
  time = time,
  event = Y_death,
  treatment = treatment,
  weights = w_pp_est,
  type = "km",
  id = id,
  trial = trial
)

summary(km_death_pp, time = 36)
summary(km_death_pp, time = 60)

plot(km_death_pp, measure = "risk")


# -----------------------------------------------------------------------------
# 1-16. Optionally compare estimated and bundled reference weights
# -----------------------------------------------------------------------------
#
# The synthetic dataset also contains reference weights constructed during
# data generation. They are not used in the main tutorial analysis.
# Because `w_itt_est` and `w_pp_est` are estimated from finite observed data,
# they are not expected to equal the bundled reference weights exactly.

# Optional comparisons:
# cor(
#   log(sglt2_long$w_itt),
#   log(sglt2_long$w_itt_est)
# )
#
# cor(
#   log(sglt2_pp$w_pp),
#   log(sglt2_pp$w_pp_est)
# )


# =============================================================================
# Interpretation map
# =============================================================================
#
# fit_death:
#   ITT hazard ratio after weighting for baseline treatment and loss to follow-up.
#
# std_death:
#   Model-based ITT survival, cumulative risk, risk difference, and risk ratio.
#
# km_death:
#   Direct IPW-weighted Kaplan-Meier estimate for the ITT pseudo-population.
#
# fit_death_pp:
#   PP hazard ratio after artificial censoring and joint-censoring weighting.
#
# std_death_pp:
#   Model-based absolute risks under sustained treatment strategies.
#
# km_death_pp:
#   Direct weighted Kaplan-Meier estimate in the PP risk set.
#
# All-cause death has no competing event in this example, so an
# Aalen-Johansen estimator is not required.
# =============================================================================

sessionInfo()

# =============================================================================
# End of the SGLT2i versus DPP-4i tutorial
# =============================================================================
